### PR TITLE
do not attempt to delete modified buffers

### PR DESCRIPTION
**Pull request by livibetter**
If plugin tries to delete a buffer is modified, error shows and that doesn't look up, so skip should be right thing to do since the buffer isn't saved.

### CODE REVIEW

**Comment by artnez** [comment]
I think the error is a good thing. The intention is to destroy all buffers that aren't open. Adding a bang (`Wipeout!`) will destroy buffers even if they are modified.

What's the use case for running `:Wipeout` and ignoring unmodified hidden buffers?

**Comment by livibetter** [comment]
I must say I strongly disagree "the error is a good thing." That kind of error shouldn't be seen like that, it should be more subtle, like "Deleted 3 buffers, skipped 2 modified buffers."

You meant ignoring modified hidden buffers? I don't think I need to give a use case, you modify files, unsaved, isn't that clear enough that you need to save those files, therefore you should skip those?
Say I want to keep the current buffer and wipe everything else,

**Comment by artnez** [comment]
The use case I'm asking for is wanting to use `:Wipeout` in the first place if you have hidden modified buffers.

The purpose of the plugin, at least for me, is destroy all buffers that I'm not actively using. The assumption I'm making (knowingly, to myself) is that the only buffers I care about are open in a window or a tab. If a buffer is hidden and unchanged, then I forgot to save it and I want to be notified (loudly). 

I do agree that the error is nasty and a message along the lines of "Deleted 3 buffers, skipped 2 modified buffers" is cleaner and would fit both of our situations.

But merely skipping modified buffers doesn't solve my problem because it hides information.

**Comment by livibetter** [comment]
I am a bit of confused about "hidden unmodified buffers," why does _unmodified_ have something to do with this issue? Moreover, why do you need and want to save an unmodified buffer? Is the definition of _modified_ not what I thought in Vim?

As for skipping modified buffers, the patch does hide the information of skips, and that information should be revealed. If I add another commit for the skip number, would that make this acceptable patch?

**Comment by artnez** [comment]
Oops, I meant to say modified buffers. Updated my comment above.

> If I add another commit for the skip number, would that make this acceptable patch?

Yep!

**Comment by livibetter** [comment]
I want to delete my fork, so commenting to make sure you get a notification. I believe when I added the last commit dbaf5b4, it didn't trigger a notification.

**Comment by artnez** [comment]
Yea, I wasn't notified. Thanks for the fix!

**Pull request merged**
